//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecompania.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string sexo { get; set; }
        public string pais { get; set; }
        public string correo { get; set; }
        public string versiontelefono { get; set; }
        public string numerotelefono { get; set; }
        public string marcatelefono { get; set; }
        public string colortelefono { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
